---
name: Checks

on: [push]

jobs:
  # id of the test
  test-lint:
    # name that will be visible on github actions
    name: Test and Link
    # job running on
    runs-on: ubuntu-20.04
    # different things that run for a job
    steps:
      # logs in to the Docker hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # checks the code inside our action    
      - name: Checkout
        uses: actions/checkout@v2
      # runs the tests for our code
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      # runs the linting for our code
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"